# fly.toml app configuration file generated for mimalyzer on 2024-11-14T16:54:16Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mimalyzer'
primary_region = 'lhr'

[build]

[http_service]
  internal_port = 80
  force_https = true
  # auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
JAVA_OPTS = '-Xms250m -Xmx250m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=1m -XX:+UseStringDeduplication -XX:+DisableExplicitGC -XX:+UseCompressedOops'
